export interface Finca {
  id: string;
  title: string;
  description: string;
  location: string;
  capacity: number;
  price: number;
  rating: number;
  reviewsCount: number;
  images: string[];
  features: string[];
  video?: string;
  coordinates: {
    lat: number;
    lng: number;
  };
}

export const fincas: Finca[] = [
  {
    id: "1",
    title: "Casa Lennon",
    description:
      "Una espectacular villa rodeada de naturaleza, ideal para desconectarse y disfrutar del sol. Cuenta con piscina infinita, jacuzzi y amplias zonas verdes.",
    location: "Ricaurte - Cundinamarca",
    capacity: 16,
    price: 1700000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "/fincas/lennon/lennon1.jpg",
      "/fincas/lennon/lennon2.jpg",
      "/fincas/lennon/lennon3.jpg",
      "/fincas/lennon/lennon4.jpg",
      "/fincas/lennon/lennon5.jpg",
      "/fincas/lennon/lennon6.jpg",
      "/fincas/lennon/lennon7.jpg",
      "/fincas/lennon/lennon8.jpg",
      "/fincas/lennon/lennon9.jpg",
      "/fincas/lennon/lennonb1.jpg",
      "/fincas/lennon/lennonb2.jpg",
      "/fincas/lennon/lennonb3.jpg",
      "/fincas/lennon/lennonb4.jpg",
      "/fincas/lennon/lennonb5.jpg",
      "/fincas/lennon/lennonb6.jpg",
      "/fincas/lennon/lennonb7.jpg",
      "/fincas/lennon/lennonb8.jpg",
      "/fincas/lennon/lennonb9.jpg",
      "/fincas/lennon/lennonc1.jpg",
      "/fincas/lennon/lennonc2.jpg",
    ],
    features: [
      "Habitaciones con baño",
      "Conexión Wifi",
      "Piscina privada",
      "Asoleadoras",
      "Cocina equipada",
      "Zona de BBQ",
      "Hamacas",
      "Juegos de mesa",
      "Sala con TV",
      "Sonido",
      "Karaoke",
      "Mini bar",
      "Parqueadero",
      "Pet friendly",
    ],
    video: "/fincas/lennon/lennon.mp4",
    coordinates: {
      lat: 4.286,
      lng: -74.775,
    },
  },
  {
    id: "2",
    title: "Hacienda La Esperanza",
    description:
      "Auténtica hacienda cafetera adaptada con todas las comodidades modernas. Perfecta para grandes familias y eventos privados.",
    location: "Armenia, Quindío",
    capacity: 25,
    price: 1200000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599809275671-b5942cabc7ad?q=80&w=2069&auto=format&fit=crop",
    ],
    features: [
      "Kiosco",
      "Cancha de Fútbol",
      "Billar",
      "Cocina Integral",
      "Pet Friendly",
    ],
    coordinates: {
      lat: 4.533,
      lng: -75.681,
    },
    video: "/videos/f2.mp4",
  },
  {
    id: "3",
    title: "Finca El Refugio",
    description:
      "Acogedora finca con arquitectura rústica y vistas panorámicas a las montañas. El lugar perfecto para un retiro tranquilo.",
    location: "Villeta, Cundinamarca",
    capacity: 10,
    price: 600000,
    rating: 4.5,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2071&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2053&auto=format&fit=crop",
    ],
    features: ["Piscina", "Juegos de mesa", "Hamacas", "TV Cable"],
    coordinates: {
      lat: 5.016,
      lng: -74.473,
    },
    video: "/videos/f3.mp4",
  },
  {
    id: "4",
    title: "Casa Campestre Los Pinos",
    description:
      "Moderna casa campestre con acabados de lujo y espacios abiertos. Disfruta de la elegancia y la naturaleza en un solo lugar.",
    location: "Santa Fe de Antioquia",
    capacity: 12,
    price: 950000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?q=80&w=1925&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina Climatizada", "Jacuzzi", "Turco", "Sonido Profesional"],
    coordinates: {
      lat: 6.556,
      lng: -75.828,
    },
    video: "/videos/f4.mp4",
  },
  {
    id: "5",
    title: "Finca Las Flores",
    description:
      "Hermosa propiedad rodeada de jardines florales y árboles frutales. Un ambiente fresco y colorido para descansar.",
    location: "Chinauta, Cundinamarca",
    capacity: 18,
    price: 750000,
    rating: 4.6,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1974&auto=format&fit=crop",
    ],
    features: ["Zona de Camping", "Rana", "Tejo", "Cocina a Leña"],
    coordinates: {
      lat: 4.269,
      lng: -74.462,
    },
    video: "/videos/f5.mp4",
  },
  {
    id: "6",
    title: "Rancho Villa Luz",
    description:
      "Exclusivo rancho con caballerizas y lago privado. Ideal para los amantes de los animales y las actividades al aire libre.",
    location: "Villavicencio, Meta",
    capacity: 20,
    price: 1100000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1984&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1974&auto=format&fit=crop",
    ],
    features: ["Lago", "Caballos", "Volleyball", "Asador Grande"],
    video: "/videos/f6.mp4",
    coordinates: {
      lat: 4.142,
      lng: -73.626,
    },
  },
  {
    id: "7",
    title: "Villa Paraíso ✨",
    description:
      "Espaciosa villa moderna en el corazón de Anapoima. Perfecta para el clima cálido y relajación total. Cuenta con piscina de borde infinito y amplios jardines.",
    location: "Anapoima, Cundinamarca",
    capacity: 14,
    price: 1500000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina de borde infinito", "Jacuzzi", "BBQ", "Wifi"],
    coordinates: { lat: 4.451, lng: -74.536 },
  },
  {
    id: "8",
    title: "Eco-Refugio Cafetero ☕",
    description:
      "Vive la experiencia del café en una finca sostenible con senderos ecológicos y avistamiento de aves.",
    location: "Salento, Quindío",
    capacity: 6,
    price: 450000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fee74a62?q=80&w=1932&auto=format&fit=crop",
    ],
    features: ["Senderos ecológicos", "Eco-friendly", "Desayuno incluido"],
    coordinates: { lat: 4.637, lng: -75.57 },
  },
  {
    id: "9",
    title: "Mirador del Tolima 🌴",
    description:
      "Moderno chalet con vista a las montañas y clima ideal. Piscina privada y áreas sociales amplias.",
    location: "Carmen de Apicalá, Tolima",
    capacity: 20,
    price: 1100000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1974&auto=format&fit=crop",
    ],
    features: ["Piscina", "Vistas a las montañas", "Billar", "BBQ"],
    coordinates: { lat: 4.148, lng: -74.721 },
  },
  {
    id: "10",
    title: "Casa de Cristal 💎",
    description:
      "Arquitectura vanguardista con ventanales de piso a techo rodeada de bosque nativo.",
    location: "La Vega, Cundinamarca",
    capacity: 8,
    price: 1250000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1449156001433-31f08f89f5bc?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Chimenea", "Diseño moderno", "Bosque nativo", "Jacuzzi"],
    coordinates: { lat: 4.996, lng: -74.341 },
  },
  {
    id: "11",
    title: "Hacienda El Cafetal 🌿",
    description:
      "Tradición y lujo en una propiedad con cultivos de café y piscina de agua natural.",
    location: "Pereira, Risaralda",
    capacity: 18,
    price: 1600000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Cultivos de café", "Piscina natural", "Kiosco", "Caballos"],
    coordinates: { lat: 4.813, lng: -75.694 },
  },
  {
    id: "12",
    title: "Náutico Prado ⛵",
    description:
      "Acceso directo a la represa para deportes náuticos y pesca. Un paraíso escondido.",
    location: "Prado, Tolima",
    capacity: 15,
    price: 850000,
    rating: 4.6,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2073&auto=format&fit=crop",
    ],
    features: ["Acceso al lago", "Lancha", "Deportes Náuticos", "BBQ"],
    coordinates: { lat: 3.744, lng: -74.929 },
  },
  {
    id: "13",
    title: "Villa Toscana 🏡",
    description:
      "Inspirada en el estilo mediterráneo, esta finca ofrece paz y vistas inmejorables.",
    location: "Mesitas del Colegio, Cundinamarca",
    capacity: 12,
    price: 800000,
    rating: 4.5,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1980&auto=format&fit=crop",
    ],
    features: ["Piscina", "Vistas panorámicas", "Wifi", "Hamacas"],
    coordinates: { lat: 4.583, lng: -74.45 },
  },
  {
    id: "14",
    title: "Montaña Mágica 🏔️",
    description:
      "Cabañas de madera en lo alto de la montaña, ideal para parejas y grupos pequeños.",
    location: "Filandia, Quindío",
    capacity: 4,
    price: 350000,
    rating: 5.0,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1965&auto=format&fit=crop",
    ],
    features: ["Chimenea", "Vistas a la montaña", "Balcón", "Aves"],
    coordinates: { lat: 4.673, lng: -75.66 },
  },
  {
    id: "15",
    title: "Portal del Sol ☀️",
    description:
      "Finca familiar con gran piscina, canchas deportivas y zona de juegos infantil.",
    location: "Melgar, Tolima",
    capacity: 30,
    price: 1300000,
    rating: 4.4,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina Olímpica", "Cancha de Fútbol", "Voley", "Kiosco"],
    coordinates: { lat: 4.204, lng: -74.642 },
  },
  {
    id: "16",
    title: "Brisa de la Mesa 🍃",
    description:
      "Clima perfecto y brisa constante en una casa de diseño abierto y minimalista.",
    location: "La Mesa, Cundinamarca",
    capacity: 10,
    price: 900000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina", "Diseño minimalista", "BBQ", "Wifi"],
    coordinates: { lat: 4.632, lng: -74.46 },
  },
  {
    id: "17",
    title: "Chalet Manizales 🎿",
    description:
      "Tradición caldense en una propiedad con jardines de flores y vista al nevado.",
    location: "Manizales, Caldas",
    capacity: 12,
    price: 700000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1974&auto=format&fit=crop",
    ],
    features: [
      "Jardines florales",
      "Vistas al Nevado",
      "Cocina Integral",
      "Chimenea",
    ],
    coordinates: { lat: 5.068, lng: -75.517 },
  },
  {
    id: "18",
    title: "Palmar Tropical 🥥",
    description:
      "Rodeada de palmeras, esta finca ofrece privacidad y un ambiente caribeño en el interior.",
    location: "Guamo, Tolima",
    capacity: 16,
    price: 650000,
    rating: 4.5,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1511520668478-f684a0d9b4c0?q=80&w=1964&auto=format&fit=crop",
    ],
    features: ["Palmeras tropicales", "Piscina", "BBQ", "Hamacas"],
    coordinates: { lat: 4.032, lng: -74.969 },
  },
  {
    id: "19",
    title: "Altos de Villeta 🎡",
    description:
      "Ubicación privilegiada con vista panorámica de 360 grados y piscina sin fin.",
    location: "Villeta, Cundinamarca",
    capacity: 22,
    price: 1800000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina sin fin", "Jacuzzi", "Mirador panorámico", "Sonido"],
    coordinates: { lat: 5.016, lng: -74.473 },
  },
  {
    id: "20",
    title: "Quinta Montenegro 🎠",
    description:
      "Cerca de los parques temáticos, ideal para grupos que buscan aventura y confort.",
    location: "Montenegro, Quindío",
    capacity: 14,
    price: 1000000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1628744276229-c83470af5ee3?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Piscina",
      "Juegos de Mesa",
      "Cerca a parques temáticos",
      "Kiosco",
    ],
    coordinates: { lat: 4.566, lng: -75.75 },
  },
  {
    id: "21",
    title: "Santuario Honda ⛪",
    description:
      "Casa colonial restaurada en la ciudad de los puentes. Historia y frescura.",
    location: "Honda, Tolima",
    capacity: 8,
    price: 550000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1590059132224-2c77d6ad8cd1?q=80&w=1974&auto=format&fit=crop",
    ],
    features: [
      "Centro Histórico",
      "Piscina",
      "Arquitectura Colonial",
      "Vistas al río",
    ],
    coordinates: { lat: 5.204, lng: -74.741 },
  },
  {
    id: "22",
    title: "Nube de Anapoima ☁️",
    description:
      "Elegancia minimalista con amplios espacios sociales y confort premium.",
    location: "Anapoima, Cundinamarca",
    capacity: 18,
    price: 2200000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Confort de lujo", "Piscina", "Salón de Cine", "Jacuzzi"],
    coordinates: { lat: 4.45, lng: -74.536 },
  },
  {
    id: "23",
    title: "Mirador Armenia 🌄",
    description:
      "Finca de descanso con vista al valle y clima templado constante.",
    location: "Armenia, Quindío",
    capacity: 12,
    price: 850000,
    rating: 4.6,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Vista al Valle", "Piscina", "Wifi", "Kiosco"],
    coordinates: { lat: 4.533, lng: -75.681 },
  },
  {
    id: "24",
    title: "Tropical Mariquita 🥭",
    description: "Finca frutal amplia con grandes zonas de recreación.",
    location: "Mariquita, Tolima",
    capacity: 25,
    price: 900000,
    rating: 4.4,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Zonas Verdes amplias", "Piscina", "BBQ", "Cancha de Fútbol"],
    coordinates: { lat: 5.202, lng: -74.891 },
  },
  {
    id: "25",
    title: "Refugio del Bosque 🌲",
    description:
      "Cabañas rústicas para una desconexión total rodeado de naturaleza salvaje.",
    location: "La Vega, Cundinamarca",
    capacity: 6,
    price: 500000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Chimenea", "Vistas a la montaña", "Eco-friendly", "Hamacas"],
    coordinates: { lat: 4.996, lng: -74.341 },
  },
  {
    id: "26",
    title: "Finca La Suiza 🧀",
    description:
      "Espectacular propiedad con arquitectura moderna y vistas al valle del Quindío.",
    location: "Pijao, Quindío",
    capacity: 10,
    price: 750000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Vistas panorámicas", "Chimenea", "Jardines", "Cafetales"],
    coordinates: { lat: 4.333, lng: -75.7 },
  },
  {
    id: "27",
    title: "Casa Arriba ⛰️",
    description:
      "Localizada en la parte más alta de la vereda, ofrece la mejor vista de la región.",
    location: "Apulo, Cundinamarca",
    capacity: 15,
    price: 1100000,
    rating: 4.6,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Mirador", "Piscina", "Jacuzzi", "BBQ"],
    coordinates: { lat: 4.516, lng: -74.593 },
  },
  {
    id: "28",
    title: "Hacienda Los Mangos 🥭",
    description:
      "Paraíso frutal con extensas áreas verdes y gran piscina social.",
    location: "Espinal, Tolima",
    capacity: 20,
    price: 700000,
    rating: 4.5,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Árboles de Mango", "Zonas Verdes", "Piscina", "Billar"],
    coordinates: { lat: 4.149, lng: -74.887 },
  },
  {
    id: "29",
    title: "Paraíso Pereira 🌸",
    description:
      "Moderna casa campestre dentro de conjunto cerrado con total seguridad.",
    location: "Pereira, Risaralda",
    capacity: 12,
    price: 1200000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Seguridad 24/7",
      "Piscina",
      "Jacuzzi",
      "Wifi de alta velocidad",
    ],
    coordinates: { lat: 4.813, lng: -75.694 },
  },
  {
    id: "30",
    title: "Brisa de Melgar 🌬️",
    description:
      "Clásica finca de Melgar ideal para grandes celebraciones y eventos.",
    location: "Melgar, Tolima",
    capacity: 40,
    price: 1600000,
    rating: 4.3,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1544984243-ec37ae96fe78?q=80&w=1974&auto=format&fit=crop",
    ],
    features: [
      "Gran Capacidad",
      "Piscina grande",
      "Salón de Eventos",
      "Cancha de Fútbol",
    ],
    coordinates: { lat: 4.204, lng: -74.642 },
  },
  {
    id: "31",
    title: "Villa Mágica ✨",
    description:
      "Encanto rústico con todas las comodidades de la vida moderna.",
    location: "Silvania, Cundinamarca",
    capacity: 18,
    price: 950000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina", "Jacuzzi", "Hamacas", "Wifi"],
    coordinates: { lat: 4.404, lng: -74.385 },
  },
  {
    id: "32",
    title: "Mirador Filandia 👁️",
    description:
      "Ubicada en el pueblo más encantador, ofrece vistas únicas al departamento.",
    location: "Filandia, Quindío",
    capacity: 8,
    price: 600000,
    rating: 5.0,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Vistas al Pueblo", "Chimenea", "Desayuno Local", "Ecológico"],
    coordinates: { lat: 4.673, lng: -75.66 },
  },
  {
    id: "33",
    title: "Eco Casa Tolima 🍃",
    description:
      "Propiedad construida con materiales locales, integrada perfectamente al paisaje.",
    location: "Flandes, Tolima",
    capacity: 10,
    price: 450000,
    rating: 4.6,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Diseño Bioclimático", "Piscina", "Wifi", "BBQ"],
    coordinates: { lat: 4.288, lng: -74.811 },
  },
  {
    id: "34",
    title: "Casa de Campo Ricaurte 🏠",
    description:
      "Finca de descanso clásica para familias numerosas en zona de alta valorización.",
    location: "Ricaurte, Cundinamarca",
    capacity: 24,
    price: 1300000,
    rating: 4.5,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Piscina", "Billar", "Rana", "Juego de Tejo"],
    coordinates: { lat: 4.286, lng: -74.775 },
  },
  {
    id: "35",
    title: "Finca Los Arrayanes 🌸",
    description:
      "Elegancia cafetera con plantaciones propias y tours privados de café.",
    location: "Circasia, Quindío",
    capacity: 12,
    price: 1100000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Tour de Café", "Piscina", "Mirador", "Jacuzzi"],
    coordinates: { lat: 4.616, lng: -75.633 },
  },
  {
    id: "36",
    title: "Mirador Girardot 🌉",
    description:
      "Vista espectacular de la ciudad y el río Magdalena desde la piscina infinita.",
    location: "Ricaurte, Cundinamarca",
    capacity: 20,
    price: 1900000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Vista al Río Magdalena",
      "Piscina Infinita",
      "Zona de Bar",
      "Wifi",
    ],
    coordinates: { lat: 4.286, lng: -74.775 },
  },
  {
    id: "37",
    title: "Rancho Tolima Grande 🐂",
    description:
      "Propiedad extensa con lago de pesca y senderos para caminatas.",
    location: "Guamo, Tolima",
    capacity: 25,
    price: 800000,
    rating: 4.4,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Lago de Pesca",
      "Senderos para caminar",
      "Piscina",
      "Cancha de Fútbol",
    ],
    coordinates: { lat: 4.032, lng: -74.969 },
  },
  {
    id: "38",
    title: "Chalet Pereira Real 🏰",
    description:
      "Un pedazo de Europa en medio del Eje Cafetero. Lujo y comodidad absoluta.",
    location: "Pereira, Risaralda",
    capacity: 10,
    price: 1400000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1980&auto=format&fit=crop",
    ],
    features: [
      "Jacuzzi Climatizado",
      "Vistas Premium",
      "Sistema de Domótica",
      "Wifi Fibra",
    ],
    coordinates: { lat: 4.813, lng: -75.694 },
  },
  {
    id: "39",
    title: "Esencia de Villeta 🍃",
    description:
      "Diseño minimalista integrado a la roca y el paisaje natural de la zona.",
    location: "Villeta, Cundinamarca",
    capacity: 12,
    price: 1500000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1449156001433-31f08f89f5bc?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Arquitectura de Vanguardia",
      "Piscina Climatizada",
      "Jacuzzi",
      "Vistas",
    ],
    coordinates: { lat: 5.016, lng: -74.473 },
  },
  {
    id: "40",
    title: "Postal Salento 📮",
    description:
      "Ubicación estratégica para visitar el Valle de Cocora y disfrutar de la paz del campo.",
    location: "Salento, Quindío",
    capacity: 6,
    price: 400000,
    rating: 5.0,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1965&auto=format&fit=crop",
    ],
    features: [
      "Cerca al Valle de Cocora",
      "Chimenea",
      "Vistas panorámicas",
      "Huerta orgánica",
    ],
    coordinates: { lat: 4.637, lng: -75.57 },
  },
  {
    id: "41",
    title: "Estancia Tolima 🤠",
    description: "Amplias zonas verdes de recreación y descanso familiar.",
    location: "Ibagué, Tolima",
    capacity: 18,
    price: 900000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Clima Templado", "Piscina", "Wifi", "Zona BBQ"],
    coordinates: { lat: 4.438, lng: -75.232 },
  },
  {
    id: "42",
    title: "Brisa de Anapoima Luxury 💎",
    description:
      "Exclusividad y confort en uno de los mejores climas del mundo.",
    location: "Anapoima, Cundinamarca",
    capacity: 22,
    price: 2800000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Lujo Extremo",
      "Personal de Servicio incluído",
      "Piscina Infinita",
      "Sala de Cine",
    ],
    coordinates: { lat: 4.45, lng: -74.536 },
  },
  {
    id: "43",
    title: "Finca Cafetalera Pijao ☕",
    description:
      "Inmersión total en la cultura cafetera en una vereda tranquila y segura.",
    location: "Pijao, Quindío",
    capacity: 14,
    price: 700000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Inmersión Cafetalera", "Senderos", "Piscina Natural", "Kiosco"],
    coordinates: { lat: 4.333, lng: -75.7 },
  },
  {
    id: "44",
    title: "Paraíso Carmen 🌴",
    description:
      "Finca moderna para vacaciones familiares con todas las amenidades.",
    location: "Carmen de Apicalá, Tolima",
    capacity: 18,
    price: 1100000,
    rating: 4.6,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1974&auto=format&fit=crop",
    ],
    features: ["Piscina", "Jacuzzi", "Mesa de Billar", "Wifi"],
    coordinates: { lat: 4.148, lng: -74.721 },
  },
  {
    id: "45",
    title: "Mirador la Vega 🏔️",
    description:
      "Increíble vista sobre el valle de La Vega, clima fresco y reparador.",
    location: "La Vega, Cundinamarca",
    capacity: 10,
    price: 850000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1449156001433-31f08f89f5bc?q=80&w=2070&auto=format&fit=crop",
    ],
    features: ["Vistas al Valle", "Jacuzzi", "Chimenea", "Wifi"],
    coordinates: { lat: 4.996, lng: -74.341 },
  },
  {
    id: "46",
    title: "Chalet Manizales Luxury ✨",
    description:
      "Experiencia premium en las montañas de Caldas con vista al nevado.",
    location: "Manizales, Caldas",
    capacity: 8,
    price: 1100000,
    rating: 5.0,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1974&auto=format&fit=crop",
    ],
    features: [
      "Vista privilegiada al Nevado",
      "Baño Turco",
      "Cava de Vinos",
      "Wifi Fibra",
    ],
    coordinates: { lat: 5.068, lng: -75.517 },
  },
  {
    id: "47",
    title: "Finca Melgar Real 👑",
    description: "Lujosa propiedad en Melgar para grupos VIP y celebridades.",
    location: "Melgar, Tolima",
    capacity: 25,
    price: 2500000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Piscina de Lujo",
      "Jacuzzi Gigante",
      "Seguridad Privada",
      "Servicio de Barman",
    ],
    coordinates: { lat: 4.204, lng: -74.642 },
  },
  {
    id: "48",
    title: "Casa de Piedra Anapoima 🗿",
    description:
      "Materiales nobles y diseño orgánico en una propiedad icónica de la zona.",
    location: "Anapoima, Cundinamarca",
    capacity: 12,
    price: 1700000,
    rating: 4.8,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=2070&auto=format&fit=crop",
    ],
    features: [
      "Diseño Arquitectónico Único",
      "Piscina",
      "Privacidad Total",
      "Wifi",
    ],
    coordinates: { lat: 4.45, lng: -74.536 },
  },
  {
    id: "49",
    title: "Eco Finca Montenegro ♻️",
    description: "Vive el Eje Cafetero de forma auténtica y sostenible.",
    location: "Montenegro, Quindío",
    capacity: 10,
    price: 600000,
    rating: 4.7,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fee74a62?q=80&w=1932&auto=format&fit=crop",
    ],
    features: [
      "100% Sostenible",
      "Senderos ecológicos",
      "Cultivos Bio",
      "Zona de Hamacas",
    ],
    coordinates: { lat: 4.566, lng: -75.75 },
  },
  {
    id: "50",
    title: "Mirador Honda 🌉",
    description:
      "Propiedad exclusiva con la mejor vista de la ciudad colonial y el río Magdalena.",
    location: "Honda, Tolima",
    capacity: 12,
    price: 850000,
    rating: 4.9,
    reviewsCount: 120,
    images: [
      "https://images.unsplash.com/photo-1590059132224-2c77d6ad8cd1?q=80&w=1974&auto=format&fit=crop",
    ],
    features: [
      "Vistas Hondanenses",
      "Piscina Sin Fin",
      "Arquitectura Colonial",
      "Wifi",
    ],
    coordinates: { lat: 5.204, lng: -74.741 },
  },
];
